name: trusttunnel_client_app
description: Source-built TrustTunnel client for iOS, macOS, and Windows
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  code_text_field: 1.1.0
  flutter:
    sdk: flutter
  flutter_highlight: 0.7.0
  path: 1.9.1
  provider: 6.1.5
  toml: 0.16.0

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  pigeon: 25.5.0

flutter:
  uses-material-design: true
